name: hexlet-ci-app-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup project
        run: make setup

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
